### PR TITLE
Pull Request for code review

### PR DESCRIPTION
**Pull request by menyagah**
# In this section I did the following:
 - Created the header.
 - Added the logo.
- Added the search bar and burger icon
 - Added the main background image.
 - Added the content section.
 - Embedded a youTube Video.
 - Added the footer.

### CODE REVIEW

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Under Review By Tolulope Olusakin(TSE)
Please check on this inside the next 30 minutes for some feedback! 🤝

**Comment by nikasulo** [comment]
# This is really great work! @menyagah 🤝 
I like how neatly it presents. Please consider my comments below, there are a few sections that require a second look. Make the required changes and submit for another review.

#### Sections Encroaching into one another
Please take a look at the screenshots I have attached below, for some reason, you have sections running into each other which is clearly not the intended behaviour, please look into these and make the necessary adjustments 🤝 

screenshot
screenshot
screenshot


##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Comment by menyagah** [comment]
Thank you so much for the feedback. I believe I changed some classes a
reason the sections are overlapping. I am working on it ASAP.

**Comment by menyagah** [comment]
Hello Tolulope.

Thank you very much for the review. I am looking at it as we speak and I'm
not finding the issues presented on the email. May I ask, was I supposed to
make the website mobile friendly? Because it is not

I have messaged you on slack.

**Comment by menyagah** [comment]
I made some changes, kindly check it.

**Comment by nikasulo** [comment]
Hello @menyagah , thank you for reaching out! I understand responsiveness isn't part of the requirements, however, it should at least present the same way across desktop type devices :ok_hand:

**Review by nikasulo — APPROVED** [review]
# Great job! @menyagah :1st_place_medal: 
It presents properly now, really fantastic work! That being said, you may merge and keep moving forward. I wish you the very best in your endeavours :ok_hand: and see you at the top :rocket: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Pull request merged**
